[package]
name = "oyster"
version = "0.1.0"
edition = "2018"

[dependencies]
num-bigint = { version = "0.4", features = ["rand"] }
num-traits = "0.2.14"
num-integer = "0.1"
rand = "0.8.4"
serde = { version = "1.0", features = ["derive"] }
